@echo off
echo Starting SafeSite Services...

echo Starting MongoDB...
start "MongoDB" cmd /k ""C:\Program Files\MongoDB\Server\8.2\bin\mongod.exe" --dbpath "D:\safesite\data\db" --port 27017"

echo Starting Backend...
start "Backend" cmd /k "cd /d D:\safesite\backend && venv\Scripts\python.exe -m uvicorn main:app --host 0.0.0.0 --port 8000"

echo Starting Frontend...
start "Frontend" cmd /k "cd /d D:\safesite\frontend && npm run dev"

echo Starting AI Service (3 Cameras)...
start "AI Cameras" cmd /k "cd /d D:\safesite\ai_service && venv\Scripts\python.exe run_all.py"

echo All services launched! Check the new windows that opened.
